const SHEET_URL='https://docs.google.com/spreadsheets/d/e/2PACX-1vSGT9g-Hpp8Ql21aTvDaHaixurmHgrja7_00wC6bPrDDFQ0NEauiz1rFZDlhgh8QBJsttjUsqQNFu99/pub?gid=1311976573&single=true&output=csv';
let agrupaciones=[];
const icon=(name,cls='icon')=>{const p={mask:'<path d="M10 2c3 2 6 2 8 0v7c0 5-4 9-8 11-4-2-8-6-8-11V2c2 2 5 2 8 0Z"/><path d="M6 9h.01M14 9h.01M7 14c2 1 4 1 6 0"/>',users:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/>',image:'<rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="9" cy="9" r="2"/><path d="m21 15-3.1-3.1a2 2 0 0 0-2.8 0L6 21"/>',map:'<path d="M14 18 9 21l-5-3V6l5 3 5-3 6 3v12l-6-3Z"/><path d="M9 9v12M14 6v12"/>',clock:'<circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/>',mail:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/>',search:'<circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/>',video:'<path d="m22 8-6 4 6 4V8Z"/><rect x="2" y="6" width="14" height="12" rx="2"/>',file:'<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8Z"/><path d="M14 2v6h6"/>',music:'<path d="M9 18V5l12-2v13"/><circle cx="6" cy="18" r="3"/><circle cx="18" cy="16" r="3"/>',lock:'<rect x="3" y="11" width="18" height="11" rx="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/>',home:'<path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2Z"/><path d="M9 22V12h6v10"/>',star:'<path d="m12 2 3.09 6.26L22 9.27l-5 4.87L18.18 21 12 17.77 5.82 21 7 14.14l-5-4.87 6.91-1.01L12 2Z"/>',user:'<path d="M20 21a8 8 0 0 0-16 0"/><circle cx="12" cy="7" r="4"/>',award:'<circle cx="12" cy="8" r="6"/><path d="M15.477 12.89 17 22l-5-3-5 3 1.523-9.11"/>'};return `<svg class="${cls}" viewBox="0 0 24 24">${p[name]||p.file}</svg>`}
function parseCSV(text){const rows=[];let row=[],cur='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){cur+='"';i++;continue}if(c==='"'){q=!q;continue}if(c===','&&!q){row.push(cur);cur='';continue}if((c==='\n'||c==='\r')&&!q){if(cur||row.length){row.push(cur);rows.push(row);row=[];cur=''}if(c==='\r'&&n==='\n')i++;continue}cur+=c}if(cur||row.length){row.push(cur);rows.push(row)}return rows}
const clean=s=>(s||'').trim();
function splitList(v){return clean(v).split(/\s*[;|]\s*/).map(x=>x.trim()).filter(Boolean)}
function modalidadClase(v){let m=clean(v).toLowerCase();if(m.includes('chirigota'))return'chirigota';if(m.includes('comparsa'))return'comparsa';if(m.includes('coro'))return'coro';if(m.includes('cuarteto'))return'cuarteto';if(m.includes('murga'))return'murga';return 'sin-modalidad'}
function colorModalidad(m){return {chirigota:'#f91669',comparsa:'#3986ff',coro:'#48bb75',cuarteto:'#fb5608',murga:'#9b59b6'}[m]||'#3986ff'}
async function cargarDatos(){try{const res=await fetch(SHEET_URL+'&t='+Date.now());const csv=await res.text();const rows=parseCSV(csv).filter(r=>r.some(Boolean));if(!rows.length)throw new Error('Hoja vacía');const headers=rows[0].map(h=>clean(h));agrupaciones=rows.slice(1).map((r,i)=>{const it={};headers.forEach((h,j)=>it[h]=clean(r[j]));const mod=modalidadClase(it['Modalidad']);return{id:i+1,nombre:it['Nombre de la agrupación']||'Sin nombre',año:it['Año de la agrupación']||'',modalidad:mod,municipio:it['Municipio del Campo de Gibraltar']||'',autores:splitList(it['Autores']),componentes:splitList(it['Componentes']),premios:splitList(it['Premios / Palmarés']),desc:it['Descripción, anécdotas o información adicional']||'',foto:it['Fotografía']||it['Foto']||'',tags:[it['Municipio del Campo de Gibraltar'],it['Modalidad'],it['Año de la agrupación']].filter(Boolean),color:colorModalidad(mod)}}).filter(a=>a.nombre&&a.nombre!=='Sin nombre');renderAll()}catch(e){console.error(e);renderAll(true)}}
function stat(){const a=agrupaciones.length, m=new Set(agrupaciones.map(x=>x.municipio).filter(Boolean)).size, y=new Set(agrupaciones.map(x=>x.año).filter(Boolean)).size;document.querySelectorAll('[data-stat="agrupaciones"]').forEach(x=>x.textContent=a);document.querySelectorAll('[data-stat="municipios"]').forEach(x=>x.textContent=m);document.querySelectorAll('[data-stat="anos"]').forEach(x=>x.textContent=y)}
function card(a){return `<article class="card"><div class="card-top" style="background:linear-gradient(135deg,${a.color},#111)"><h3>${a.nombre}</h3></div><div class="card-body"><div class="meta"><span class="tag">${a.año||'Sin año'}</span><span class="tag">${a.modalidad}</span><span class="tag">${a.municipio||'Sin municipio'}</span></div><p>${a.desc||'Ficha pendiente de ampliar.'}</p><p style="margin-top:12px"><a class="author-link" href="agrupacion.html?id=${a.id}">Ver ficha completa</a></p></div></article>`}
function renderAgrupaciones(list=agrupaciones){const el=document.querySelector('[data-agrupaciones]');if(!el)return;if(!list.length){el.innerHTML='<div class="empty">Todavía no hay agrupaciones publicadas. Cuando entren datos del formulario aparecerán aquí.</div>';return}el.innerHTML=list.map(card).join('')}
function renderDestacadas(){const el=document.querySelector('[data-destacadas]');if(!el)return;const destacadas=JSON.parse(localStorage.getItem('destacadas')||'[]');const list=destacadas.length?agrupaciones.filter(a=>destacadas.includes(String(a.id))):agrupaciones.slice(0,6);renderAgrupacionesInto(el,list)}
function renderAgrupacionesInto(el,list){el.innerHTML=list.length?list.map(card).join(''):'<div class="empty">Sin destacadas por ahora.</div>'}
function renderFototeca(){const el=document.querySelector('[data-fototeca]');if(!el)return;const conFoto=agrupaciones.filter(a=>a.foto);if(!conFoto.length){el.innerHTML='<div class="empty">La fototeca aparecerá cuando añadas enlaces de imágenes en la hoja.</div>';return}el.innerHTML=conFoto.map(a=>`<article class="media"><div class="thumb" style="background-image:url('${a.foto}');background-size:cover;background-position:center"></div><div><b>${a.nombre}</b><p>${a.año} · ${a.municipio}</p></div></article>`).join('')}
function renderVideos(){const el=document.querySelector('[data-videos]');if(el)el.innerHTML='<div class="empty">Sección preparada. Añade una columna “Vídeo” en la hoja para enlazar YouTube, Vimeo o Drive.</div>'}
function renderMunicipios(){const el=document.querySelector('[data-municipios]');if(!el)return;const municipios=['La Línea','Algeciras','San Roque','Los Barrios','Tarifa','Jimena','Castellar','Tesorillo'];el.innerHTML=municipios.map(m=>{const list=agrupaciones.filter(a=>a.municipio.toLowerCase().includes(m.toLowerCase().split(' ')[0]));return `<article class="card"><div class="card-top" style="background:linear-gradient(135deg,var(--verde),#111)"><h3>${m}</h3></div><div class="card-body"><p><b>${list.length}</b> agrupaciones registradas.</p><p style="margin-top:12px">${list.slice(0,5).map(x=>x.nombre).join(', ')||'Pendiente de documentación.'}</p></div></article>`}).join('')}
function renderAutores(){const el=document.querySelector('[data-autores]');if(!el)return;const map=new Map();agrupaciones.forEach(a=>a.autores.forEach(n=>{if(!map.has(n))map.set(n,[]);map.get(n).push(a)}));const arr=[...map.entries()].sort((a,b)=>a[0].localeCompare(b[0]));el.innerHTML=arr.length?arr.map(([n,l])=>`<article class="card"><div class="card-body"><h3>${icon('user')} <a class="author-link" href="autor.html?nombre=${encodeURIComponent(n)}">${n}</a></h3><p>${l.length} agrupación/es vinculada/s.</p></div></article>`).join(''):'<div class="empty">Los autores aparecerán cuando se rellene ese campo en la hoja.</div>'}
function renderFichaAgrupacion(){const el=document.querySelector('[data-ficha]');if(!el)return;const id=new URLSearchParams(location.search).get('id');const a=agrupaciones.find(x=>String(x.id)===String(id));if(!a){el.innerHTML='<div class="empty">No se encontró esta agrupación.</div>';return}el.innerHTML=`<div class="box"><h2 class="serif" style="font-size:40px">${a.nombre}</h2><div class="meta" style="margin:16px 0"><span class="tag">${a.año}</span><span class="tag">${a.modalidad}</span><span class="tag">${a.municipio}</span></div><p style="line-height:1.8">${a.desc||'Sin descripción.'}</p><h3 style="margin-top:24px">Autores</h3><p>${a.autores.map(n=>`<a class="pill author-link" href="autor.html?nombre=${encodeURIComponent(n)}">${n}</a>`).join('')||'No indicado'}</p><h3 style="margin-top:18px">Componentes</h3><p>${a.componentes.map(n=>`<span class="pill">${n}</span>`).join('')||'No indicado'}</p><h3 style="margin-top:18px">Premios / Palmarés</h3><p>${a.premios.map(n=>`<span class="pill">${n}</span>`).join('')||'No indicado'}</p></div>`}
function renderAutor(){const el=document.querySelector('[data-autor]');if(!el)return;const n=new URLSearchParams(location.search).get('nombre')||'';const list=agrupaciones.filter(a=>a.autores.includes(n)||a.componentes.includes(n));el.innerHTML=`<div class="profile"><div class="avatar">${icon('user','icon')}</div><div><h2 class="serif" style="font-size:44px">${n||'Autor'}</h2><p style="line-height:1.8;margin:14px 0">Perfil documental de ${n}. Aquí se agrupan las agrupaciones, fotografías y materiales vinculados a esta persona.</p><h3>Agrupaciones vinculadas</h3><div class="cards" style="margin-top:18px">${list.map(card).join('')||'<div class="empty">Sin resultados.</div>'}</div></div></div>`}
function renderCronologia(){const el=document.querySelector('[data-cronologia]');if(!el)return;const years=[...new Set(agrupaciones.map(a=>a.año).filter(Boolean))].sort();el.innerHTML=years.length?years.map(y=>`<div class="box" style="margin-bottom:14px"><h3>${y}</h3><p>${agrupaciones.filter(a=>a.año===y).map(a=>a.nombre).join(', ')}</p></div>`).join(''):'<div class="empty">La cronología se generará automáticamente con los años recibidos.</div>'}
function renderAll(err=false){stat();renderAgrupaciones();renderDestacadas();renderFototeca();renderVideos();renderMunicipios();renderAutores();renderFichaAgrupacion();renderAutor();renderCronologia();if(err){document.querySelectorAll('[data-error]').forEach(e=>e.textContent='No se pudieron cargar los datos de Google Sheets. Revisa que la hoja esté publicada como CSV.') }}
function setupFilters(){document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const f=b.dataset.filter;renderAgrupaciones(f==='todas'?agrupaciones:agrupaciones.filter(a=>a.modalidad===f))}));const q=document.querySelector('[data-search]');if(q)q.addEventListener('input',()=>{const v=q.value.toLowerCase();renderAgrupaciones(agrupaciones.filter(a=>[a.nombre,a.municipio,a.modalidad,a.año,...a.autores,...a.componentes].join(' ').toLowerCase().includes(v)))})}
function adminLogin(){const code=document.getElementById('adminCode')?.value;if(code==='CARNAVAL2026'){localStorage.setItem('admin','1');document.querySelector('.admin-panel')?.classList.add('open')}else alert('Código incorrecto')}
function guardarDestacadas(){const v=document.getElementById('destacadasIds').value.split(',').map(x=>x.trim()).filter(Boolean);localStorage.setItem('destacadas',JSON.stringify(v));alert('Destacadas guardadas en este navegador. Para control real hay que usar backend.');renderDestacadas()}
function toggleMobileNav(){document.getElementById('mobileNav')?.classList.toggle('open')}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('[data-icon]').forEach(e=>e.innerHTML=icon(e.dataset.icon,e.className||'icon'));setupFilters();if(localStorage.getItem('admin')==='1')document.querySelector('.admin-panel')?.classList.add('open');cargarDatos()});
