const SHEET_URL='https://docs.google.com/spreadsheets/d/e/2PACX-1vSGT9g-Hpp8Ql21aTvDaHaixurmHgrja7_00wC6bPrDDFQ0NEauiz1rFZDlhgh8QBJsttjUsqQNFu99/pub?gid=1311976573&single=true&output=csv';
const REQUIRED=['Municipio del Campo de Gibraltar','Nombre de la agrupación','Año de la agrupación','Modalidad'];
let agrupaciones=[];
const icon={mask:'<svg class="icon" viewBox="0 0 24 24"><path d="M4 4c3 0 5 1 8 1s5-1 8-1c1 0 2 1 2 2v5c0 5-4 9-8 9-1.5 0-3-1-4-2-1 1-2.5 2-4 2-4 0-8-4-8-9V6c0-1 1-2 2-2Zm4 8c1 0 2-.7 2-1.5S9 9 8 9s-2 .7-2 1.5S7 12 8 12Zm8 0c1 0 2-.7 2-1.5S17 9 16 9s-2 .7-2 1.5S15 12 16 12Zm-7 4h6c-.6-1.2-1.5-2-3-2s-2.4.8-3 2Z"/></svg>',search:'<svg class="icon" viewBox="0 0 24 24"><path d="M10 4a6 6 0 1 0 0 12 6 6 0 0 0 0-12Zm0-2a8 8 0 0 1 6.3 12.9l4.4 4.4-1.4 1.4-4.4-4.4A8 8 0 1 1 10 2Z"/></svg>',mail:'<svg class="icon" viewBox="0 0 24 24"><path d="M3 5h18v14H3V5Zm2 3.2V17h14V8.2l-7 4.4-7-4.4Zm1.2-1.2 5.8 3.6L17.8 7H6.2Z"/></svg>',photo:'<svg class="icon" viewBox="0 0 24 24"><path d="M4 5h3l1.5-2h7L17 5h3a2 2 0 0 1 2 2v12H2V7a2 2 0 0 1 2-2Zm8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8Z"/></svg>',video:'<svg class="icon" viewBox="0 0 24 24"><path d="M3 5h14v5l4-3v10l-4-3v5H3V5Zm2 2v10h10V7H5Z"/></svg>',map:'<svg class="icon" viewBox="0 0 24 24"><path d="m9 18-6 3V6l6-3 6 3 6-3v15l-6 3-6-3Zm1-12v10l4 2V8l-4-2Z"/></svg>',clock:'<svg class="icon" viewBox="0 0 24 24"><path d="M12 2a10 10 0 1 1 0 20 10 10 0 0 1 0-20Zm1 5h-2v6l5 3 1-1.7-4-2.3V7Z"/></svg>'};
function navToggle(){document.querySelector('.navlinks')?.classList.toggle('open')}
function esc(s){return String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function slug(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function splitPeople(value){return String(value||'').split(/\s*[;|]\s*/).map(x=>x.trim()).filter(Boolean)}
function splitAwards(value){return String(value||'').split(/\s*[;|]\s*/).map(x=>x.trim()).filter(Boolean)}
function normalizeMod(m){m=String(m||'').toLowerCase(); if(m.includes('comparsa'))return'comparsa'; if(m.includes('chirigota'))return'chirigota'; if(m.includes('coro'))return'coro'; if(m.includes('cuarteto'))return'cuarteto'; if(m.includes('murga'))return'murga'; return 'sin modalidad'}
function modColor(m){return {comparsa:'#3986ff',chirigota:'#f91669',coro:'#48bb75',cuarteto:'#fb5608',murga:'#9b59b6'}[normalizeMod(m)]||'#3986ff'}
function parseCSV(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++;continue}if(c==='"'){q=!q;continue}if(c===','&&!q){row.push(cell);cell='';continue}if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell='';continue}cell+=c}row.push(cell);if(row.some(x=>x.trim()))rows.push(row);return rows}
async function loadRows(){const r=await fetch(SHEET_URL+'&cacheBust='+Date.now());const text=await r.text();const rows=parseCSV(text);if(!rows.length)return[];const heads=rows[0].map(h=>h.trim());return rows.slice(1).map((vals,i)=>{const o={_row:i+2};heads.forEach((h,idx)=>o[h]=(vals[idx]||'').trim());return o}).filter(o=>Object.values(o).some(Boolean))}
function makeGroups(rows){const map=new Map();rows.forEach(o=>{const key=[o['Municipio del Campo de Gibraltar'],o['Nombre de la agrupación'],o['Año de la agrupación'],o['Modalidad']].map(slug).join('|');if(!key.replace(/\|/g,''))return; if(!map.has(key)){map.set(key,{id:map.size+1,nombre:o['Nombre de la agrupación']||'Sin nombre',año:o['Año de la agrupación']||'',modalidad:normalizeMod(o['Modalidad']),municipio:o['Municipio del Campo de Gibraltar']||'',autores:[],componentes:[],premios:[],desc:'',fotos:[],videos:[],carteles:[],tags:[],color:modColor(o['Modalidad'])})}const g=map.get(key);g.autores.push(...splitPeople(o['Autores']));g.componentes.push(...splitPeople(o['Componentes']));g.premios.push(...splitAwards(o['Premios / Palmarés']));if(o['Descripción, anécdotas o información adicional'])g.desc += (g.desc?'\n':'')+o['Descripción, anécdotas o información adicional'];['Fotografías','Fotos','Foto','Imagen','Carteles','Cartel','Vídeos','Videos','Video'].forEach(k=>{if(o[k]){const list=String(o[k]).split(/\s*[;|]\s*/).filter(Boolean); if(k.toLowerCase().includes('cartel'))g.carteles.push(...list); else if(k.toLowerCase().includes('video')||k.toLowerCase().includes('vídeo'))g.videos.push(...list); else g.fotos.push(...list)}});g.tags=[g.municipio,g.modalidad,g.año].filter(Boolean)});return [...map.values()].map(g=>{g.autores=[...new Set(g.autores)];g.componentes=[...new Set(g.componentes)];g.premios=[...new Set(g.premios)];return g})}
async function initData(){try{const rows=await loadRows();agrupaciones=makeGroups(rows);renderStats();renderCurrent()}catch(e){console.error(e);const t=document.querySelector('[data-list]');if(t)t.innerHTML='<div class="empty"><h3>No se pudo cargar la hoja</h3><p>Revisa que Google Sheets siga publicado como CSV.</p></div>'}}
function renderStats(){const s=document.querySelectorAll('[data-stat]');if(!s.length)return;const mun=new Set(agrupaciones.map(a=>a.municipio).filter(Boolean));const yrs=new Set(agrupaciones.map(a=>a.año).filter(Boolean));const fotos=agrupaciones.reduce((n,a)=>n+a.fotos.length,0);const vals={agrupaciones:agrupaciones.length,municipios:mun.size,anios:yrs.size,fotografias:fotos};s.forEach(el=>el.textContent=vals[el.dataset.stat]??0)}
function card(a){return `<article class="card group-card"><div class="group-top" style="background:linear-gradient(135deg,${a.color}55,#0d0d0d)"><span class="pill type" style="background:${a.color}">${esc(a.modalidad)}</span><span class="pill year">${esc(a.año)}</span><h3>${esc(a.nombre)}</h3></div><div class="group-body"><div class="meta"><span>${esc(a.municipio)}</span><span>${esc(a.autores.length? a.autores.join(' · '):'Sin autores')}</span></div><p class="desc">${esc(a.desc||'Ficha pendiente de completar.')}</p><div class="person-list">${a.autores.map(p=>`<a class="person-link" href="persona.html?tipo=autor&nombre=${encodeURIComponent(p)}">${esc(p)}</a>`).join('')}${a.componentes.slice(0,4).map(p=>`<a class="person-link" href="persona.html?tipo=componente&nombre=${encodeURIComponent(p)}">${esc(p)}</a>`).join('')}</div></div></article>`}
function renderCurrent(){const page=document.body.dataset.page;if(page==='home')renderHome(); if(page==='agrupaciones')renderGroups(); if(page==='fototeca')renderMedia('fotos'); if(page==='videos')renderMedia('videos'); if(page==='municipios')renderMunicipios(); if(page==='cronologia')renderCrono(); if(page==='persona')renderPersona()}
function renderHome(){const box=document.querySelector('[data-list="featured"]');if(box)box.innerHTML=agrupaciones.slice(0,6).map(card).join('')||empty('Aún no hay agrupaciones cargadas','Cuando Jotform envíe datos a la hoja, aparecerán aquí.');}
function renderGroups(){const box=document.querySelector('[data-list="groups"]');const q=document.querySelector('#q')?.value.toLowerCase()||'';const mod=document.querySelector('.chip.active')?.dataset.mod||'todos';let data=agrupaciones.filter(a=>(mod==='todos'||a.modalidad===mod)&&JSON.stringify(a).toLowerCase().includes(q));box.innerHTML=data.map(card).join('')||empty('Sin resultados','Prueba con otro filtro o revisa la hoja de cálculo.');}
function filterMod(btn){document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));btn.classList.add('active');renderGroups()}
function renderMedia(kind){const box=document.querySelector('[data-list="media"]');let items=[];agrupaciones.forEach(a=>{(a[kind]||[]).forEach(url=>items.push({url,a}))});box.innerHTML=items.map(i=>`<article class="card"><div style="aspect-ratio:4/3;background:linear-gradient(135deg,#111,${i.a.color});border-radius:16px;display:grid;place-items:center;color:#fff;font-size:40px">${kind==='videos'?icon.video:icon.photo}</div><h3 style="margin:14px 0 6px;font-family:'Playfair Display',serif">${esc(i.a.nombre)}</h3><p class="desc">${esc(i.a.municipio)} · ${esc(i.a.año)} · ${esc(i.a.modalidad)}</p><a class="person-link" href="${esc(i.url)}" target="_blank">Abrir archivo</a></article>`).join('')||empty(kind==='videos'?'Aún no hay vídeos':'Aún no hay fotografías','Añade enlaces en la hoja usando la columna correspondiente.');}
function renderMunicipios(){const box=document.querySelector('[data-list="municipios"]');const map={};agrupaciones.forEach(a=>{if(!a.municipio)return;(map[a.municipio]??=[]).push(a)});box.innerHTML=Object.entries(map).map(([m,list])=>`<article class="card"><h3 style="font-family:'Playfair Display',serif;font-size:28px">${esc(m)}</h3><p class="desc">${list.length} agrupaciones archivadas</p><div class="person-list">${[...new Set(list.map(a=>a.modalidad))].map(x=>`<span class="person-link">${esc(x)}</span>`).join('')}</div></article>`).join('')||empty('Aún no hay municipios','Se crearán automáticamente cuando entren agrupaciones.');}
function renderCrono(){const box=document.querySelector('[data-list="crono"]');const by={};agrupaciones.forEach(a=>{const d=String(a.año).slice(0,3)+'0'; if(a.año)(by[d]??=[]).push(a)});box.innerHTML=Object.entries(by).sort().map(([d,list])=>`<article class="card"><h3 style="font-family:'Playfair Display',serif;font-size:32px">Década de ${esc(d)}</h3><p class="desc">${list.length} agrupaciones documentadas</p><div class="person-list">${list.slice(0,8).map(a=>`<span class="person-link">${esc(a.nombre)}</span>`).join('')}</div></article>`).join('')||empty('Cronología vacía','Se generará automáticamente por décadas cuando haya años en la hoja.');}
function renderPersona(){const params=new URLSearchParams(location.search);const name=params.get('nombre')||'';document.querySelector('[data-person-name]').textContent=name||'Persona';const rel=agrupaciones.filter(a=>a.autores.includes(name)||a.componentes.includes(name));document.querySelector('[data-list="personGroups"]').innerHTML=rel.map(card).join('')||empty('Sin agrupaciones vinculadas','Revisa que el nombre esté escrito igual en la hoja.');}
function empty(t,p){return `<div class="empty"><h3>${esc(t)}</h3><p>${esc(p)}</p></div>`}
function adminLogin(){const code=document.querySelector('#adminCode').value;if(code==='CAMPO2026'){localStorage.setItem('admin','1');document.querySelector('#adminArea').style.display='block';document.querySelector('#loginBox').style.display='none'}else alert('Código incorrecto')}
document.addEventListener('DOMContentLoaded',initData);
window.navToggle=navToggle;window.filterMod=filterMod;window.renderGroups=renderGroups;window.adminLogin=adminLogin;
